=== KrisDM/corinet/code/xml/Definition/codeGenerator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.corinet.org/namespaces/CORINETDefinition/Generator" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.corinet.org/namespaces/CORINETDefinition/Generator" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="codeGenerator">
		<xs:annotation>
			<xs:documentation>Schema defining C++ code template files.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="annotation" type="annotationType" minOccurs="0"/>
				<xs:element name="intro">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="line" type="lineType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="randGen">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="attenuation">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="noiseFunction">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="initialisation">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="normalisation">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="outputFunction">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="integrationSite">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="block">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="network">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dataSource">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="insert">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="task">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="compositeTask">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="hFile"/>
							<xs:element ref="cppFile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="codeFile" type="xs:anyURI" use="optional"/>
			<xs:attribute name="location" type="xs:anyURI" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="hFile">
		<xs:annotation>
			<xs:documentation>Contains code for .h file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="annotation" type="annotationType" minOccurs="0"/>
				<xs:element name="line" type="lineType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cppFile">
		<xs:annotation>
			<xs:documentation>Contains code for .cpp file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="annotation" type="annotationType" minOccurs="0"/>
				<xs:element name="line" type="lineType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="lineType" mixed="true">
		<xs:annotation>
			<xs:documentation>One line of C++ code</xs:documentation>
		</xs:annotation>
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="tab" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="insertText" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="date"/>
								<xs:enumeration value="fileName"/>
								<xs:enumeration value="typeName"/>
								<xs:enumeration value="typeNameUpper"/>
								<xs:enumeration value="key"/>
								<xs:enumeration value="params"/>
								<xs:enumeration value="getParams"/>
								<xs:enumeration value="setParams"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="annotationType">
		<xs:annotation>
			<xs:documentation>Allows to add documentation and other information</xs:documentation>
		</xs:annotation>
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="appinfo">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="source" type="xs:anyURI" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="documentation">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="source" type="xs:anyURI" use="optional"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="id" type="xs:ID" use="optional"/>
	</xs:complexType>
</xs:schema>

=== KrisDM/corinet/code/xml/Definition/codeGenerator.xml
<?xml version="1.0" encoding="UTF-8"?>
<codeGenerator xmlns="http://www.corinet.org/namespaces/CORINETDefinition/Generator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.corinet.org/namespaces/CORINETDefinition/Generator codeGenerator.xsd">
	<annotation>
		<documentation>
			Templates used for generating C++ code; please do not modify. 
		</documentation>
	</annotation>
	<intro>
		<line>/*********************************************************************************************</line>
		<line> * Name<tab/><tab/>:  <insertText type="fileName"/></line>
		<line> *</line>
		<line> * Purpose<tab/>:</line>
		<line> *</line>
		<line> * Notes<tab/>:  This file was generated by corinet on <insertText type="date"/></line>
		<line> *</line>
		<line> * Info<tab/><tab/>:  http://www.corinet.org</line>
		<line> *</line>
		<line> * Copyright:</line>
		<line> *</line>
		<line> * License<tab/>:  This program is free software; you can redistribute it and/or modify</line>
		<line> * <tab/><tab/><tab/>   it under the terms of the GNU General Public License as published by</line>
		<line> * <tab/><tab/><tab/>   the Free Software Foundation; either version 2 of the License, or</line>
		<line> * <tab/><tab/><tab/>   (at your option) any later version.</line>
		<line> *</line>
		<line> * <tab/><tab/><tab/>   This program is distributed in the hope that it will be useful,</line>
		<line> * <tab/><tab/><tab/>   but WITHOUT ANY WARRANTY; without even the implied warranty of</line>
		<line> * <tab/><tab/><tab/>   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the</line>
		<line> * <tab/><tab/><tab/>   GNU General Public License in $CORINETROOT/licenses for more details.</line>
		<line> *</line>
		<line> **********************************************************************************************/</line>
		<line></line>
	</intro>
	<randGen>
		<hFile>
			<line>#ifndef CORINET_RANDDOUBLE<insertText type="typeNameUpper"/></line>
			<line>#define CORINET_RANDDOUBLE<insertText type="typeNameUpper"/></line>
			<line></line>
			<line>#include &lt;Common/Impl/RandDoubleImpl.h&gt;</line>
			<line></line>
			<line>namespace CORINET {</line>
			<line></line>
			<line>class Rand<insertText type="typeName"/> : public RandDoubleImpl {</line>
			<line><tab/><insertText type="params"/></line>
			<line>public:</line>
			<line><tab/>Rand<insertText type="typeName"/>(size_t*,double*);</line>
			<line><tab/>virtual ~Rand<insertText type="typeName"/>();</line>
			<line><tab/>double operator()();</line>
			<line><tab/>void SetParam(size_t,double);</line>
			<line><tab/>double GetParam(size_t);</line>
			<line>};</line>
			<line></line>
			<line>} //end namespace CORINET</line>
			<line></line>
			<line>#endif //CORINET_RANDDOUBLE<insertText type="typeNameUpper"/></line>
			<line></line>
		</hFile>
		<cppFile>
			<line></line>
			<line>#include &lt;Util/Factory.h&gt;</line>
			<line>#include "<insertText type="fileName"/>"</line>
			<line></line>
			<line>namespace CORINET {</line>
			<line></line>
			<line>Rand<insertText type="typeName"/>::Rand<insertText type="typeName"/>(size_t* s,double* params)</line>
			<line>{</line>
			<line><tab/>/*parameters available in s: none*/</line>
			<line><insertText type="params"/></line>
			<line>}</line>
			<line></line>
			<line>Rand<insertText type="typeName"/>::~Rand<insertText type="typeName"/>()</line>
			<line>{</line>
			<line></line>
			<line>}</line>
			<line></line>
			<line>double Rand<insertText type="typeName"/>::operator()()</line>
			<line>{</line>
			<line><tab/>/*insert your code here*/</line>
			<line><tab/>return 0.0;</line>
			<line>}</line>
			<line></line>
			<line>void Rand<insertText type="typeName"/>::SetParam(size_t p,double v)</line>
			<line>{</line>
			<line><insertText type="setParams"/></line>
			<line>}</line>
			<line></line>
			<line>double Rand<insertText type="typeName"/>::GetParam(size_t p)</line>
			<line>{</line>
			<line><insertText type="getParams"/></line>
			<line>}</line>
			<line></line>
			<line>/*macro registers class name, see Factory.h for details*/</line>
			<line>REGISTER_CLASS_1(RandDouble,Rand<insertText type="typeName"/>,<insertText type="key"/>)</line>
			<line></line>
			<line>} //end namespace CORINET</line>
			<line></line>
		</cppFile>
	</randGen>
	<attenuation>
		<hFile>
			<line>#ifndef CORINET_ATTENUATION<insertText type="typeNameUpper"/></line>
			<line>#define CORINET_ATTENUATION<insertText type="typeNameUpper"/></line>
			<line></line>
			<line>#include &lt;Common/Impl/AttenuationImpl.h&gt;</line>
			<line></line>
			<line>namespace CORINET {</line>
			<line></line>
			<line>class FAttenuation<insertText type="typeName"/> : public FAttenuationImpl {</line>
			<line><tab/><insertText type="params"/></line>
			<line>public:</line>
			<line><tab/>FAttenuation<insertText type="typeName"/>(size_t*,double*);</line>
			<line><tab/>virtual ~FAttenuation<insertText type="typeName"/>();</line>
			<line><tab/>void Initialise();</line>
			<line><tab/>void Reset();</line>
			<line><tab/>void operator()(SubArrayIterator&amp;);</line>
			<line><tab/>void SetParam(size_t,double);</line>
			<line><tab/>double GetParam(size_t);</line>
			<line>};</line>
			<line></line>
			<line>} //end namespace CORINET</line>
			<line></line>
			<line>#endif //CORINET_ATTENUATION<insertText type="typeNameUpper"/></line>
			<line></line>
		</hFile>
		<cppFile>
			<line></line>
			<line>#include &lt;Util/Factory.h&gt;</line>
			<line>#include &lt;Util/Iterator.h&gt;</line>
			<line>#include "<insertText type="fileName"/>"</line>
			<line></line>
			<line>namespace CORINET {</line>
			<line></line>
			<line>FAttenuation<insertText type="typeName"/>::FAttenuation<insertText type="typeName"/>(size_t* s,double* params)</line>
			<line>{</line>
			<line><tab/>/*parameters available in s:</line>
			<line><tab/><tab/>s[0]: number of nodes in block or size of pattern*/</line>
			<line><insertText type="params"/></line>
			<line>}</line>
			<line></line>
			<line>FAttenuation<insertText type="typeName"/>::~FAttenuation<insertText type="typeName"/>()</line>
			<line>{</line>
			<line></line>
			<line>}</line>
			<line></line>
			<line>void FAttenuation<insertText type="typeName"/>::Initialise()</line>
			<line>{</line>
			<line><tab/>/*you may delete this function here and in .h file if no action needs to be taken*/</line>
			<line>}</line>
			<line></line>
			<line>void FAttenuation<insertText type="typeName"/>::Reset()</line>
			<line>{</line>
			<line><tab/>/*you may delete this function here and in .h file if no action needs to be taken*/</line>
			<line>}</line>
			<line></line>
			<line>void FAttenuation<insertText type="typeName"/>::operator()(SubArrayIterator&amp; y)</line>
			<line>{</line>
			<line><tab/>/*insert your code here*/</line>
			<line>}</line>
			<line></line>
			<line>void FAttenuation<insertText type="typeName"/>::SetParam(size_t p,double v)</line>
			<line>{</line>
			<line><insertText type="setParams"/></line>
			<line>}</line>
			<line></line>
			<line>double FAttenuation<insertText type="typeName"/>::GetParam(size_t p)</line>
			<line>{</line>
			<line><insertText type="getParams"/></line>
			<line>}</line>
			<line></line>
			<line>/*macro registers class name, see Factory.h for details*/</line>
			<line>REGISTER_CLASS_1(FAttenuation,FAttenuation<insertText type="typeName"/>,<insertText type="key"/>)</line>
			<line></line>
			<line>} //end namespace CORINET</line>
			<line></line>
		</cppFile>
	</attenuation>
	<noiseFunction>
		<hFile>
			<line>#ifndef CORINET_NOISEFUNCTION<insertText type="typeNameUpper"/></line>
			<line>#define CORINET_NOISEFUNCTION<insertText type="typeNameUpper"/></line>
			<line></line>
			<line>#include &lt;Common/Impl/NoiseFunctionImpl.h&gt;</line>
			<line></line>
			<line>namespace CORINET {</line>
			<line></line>
			<line>class FNoiseFunction<insertText type="typeName"/> : public FNoiseFunctionImpl {</line>
			<line><tab/><insertText type="params"/></line>
			<line>public:</line>
			<line><tab/>FNoiseFunction<insertText type="typeName"/>(size_t*,double*);</line>
			<line><tab/>virtual ~FNoiseFunction<insertText type="typeName"/>();</line>
			<line><tab/>void Initialise();</line>
			<line><tab/>void Reset();</line>
			<line><tab/>void operator()(SubArrayIterator&amp;);</line>
			<line><tab/>void SetParam(size_t,double);</line>
			<line><tab/>double GetParam(size_t);</line>
			<line>};</line>
			<line></line>
			<line>} //end namespace CORINET</line>
			<line></line>
			<line>#endif //CORINET_NOISEFUNCTION<insertText type="typeNameUpper"/></line>
			<line></line>
		</hFile>
		<cppFile>
			<line></line>
			<line>#include &lt;Util/Factory.h&gt;</line>
			<line>#include &lt;Util/Iterator.h&gt;</line>
			<line>#include "<insertText type="fileName"/>"</line>
			<line></line>
			<line>namespace CORINET {</line>
			<line></line>
			<line>FNoiseFunction<insertText type="typeName"/>::FNoiseFunction<insertText type="typeName"/>(size_t* s,double* params)</line>
			<line>{</line>
			<line><tab/>/*parameters available in s:</line>
			<line><tab/><tab/>s[0]: number of nodes in block or size of pattern*/</line>
			<line><insertText type="params"/></line>
			<line>}</line>
			<line></line>
			<line>FNoiseFunction<insertText type="typeName"/>::~FNoiseFunction<insertText type="typeName"/>()</line>
			<line>{</line>
			<line></line>
			<line>}</line>
			<line></line>
			<line>void FNoiseFunction<insertText type="typeName"/>::Initialise()</line>
			<line>{</line>
			<line><tab/>/*you may delete this function here and in .h file if no action needs to be taken*/</line>
			<line>}</line>
			<line></line>
			<line>void FNoiseFunction<insertText type="typeName"/>::Reset()</line>
			<line>{</line>
			<line><tab/>/*you may delete this function here and in .h file if no action needs to be taken*/</line>
			<line>}</line>
			<line></line>
